### ISSUE TITLE
Notemode All LEDS green after adding Instrument

### ISSUE THREAD

**Issue by daslicht** [git-moss/Push4Bitwig#160]
Hi,
after adding  a new instrument, when I hit a pad all pads illumiate green.
Switching to another Channel and coming back fixes this issue.

**Comment by git-moss** [comment]
Does that happen all the time? How do you add the instrument?
I only experienced this effect very rarely on startup but can not reproduce it. It guess it is a synchronisation issue which is hard/impossible to fix in Javascript.

**Comment by daslicht** [comment]
I get that anytime when i add an instrument using drag and drop

**Comment by git-moss** [comment]
Could you please give a step-by-step explanation, starting with an empty project?

**Comment by pikzel** [comment]
I have the same issue. I just start a new project, add an instrument track, and when I move between session and live views, it seems to lose track of what it's doing, so every pad press illuminates all of them in green.

**Comment by git-moss** [comment]
Again: Please tell me step-by-step what are you exactly doing, what plugin do you add, what buttons do you press on the Push? Is this reproducable 100%?
Also: Which platform are you on, which version are you running?

**Comment by daslicht** [comment]
I dont touch Push at all
Create a new project
Drag drop vst to arrangement view 
All green

**Comment by pikzel** [comment]
Same on OSX 10.9:
Create new project
Drop any midi device to arrangement
The pads on the Push turns green on when any "note" pad is pressed

Ableton Push 4.2 24.12.2014 from http://www.mossgrabers.de/Software/Bitwig/Bitwig.html

**Comment by git-moss** [comment]
Ah, that makes it clear! I can reproduce the problem (never added a plugin like this) now but no idea so far.

**Comment by git-moss** [comment]
I think I got it. Please test with the latest version on GitHub.
