### ISSUE TITLE
Pad modes merge

### ISSUE THREAD

**Issue by adsch** [git-moss/Push4Bitwig#162]
I don't think I can reproduce it every time, but sometimes when I switch modes. Session to Sequencer and so on.. The pads don't refresh and suddenly you're in between 2 modes. At least that what the lighting indicates.

In my photo you have a mix of Sequencer and Session mode

![bitwig_push_bug](https://cloud.githubusercontent.com/assets/10582287/6887118/757c68fc-d655-11e4-989b-5892f365243c.jpg)

**Comment by git-moss** [comment]
Hmm, pretty strange. Never had that myself. I fear without a reproduction hint I can't do anything about it.

**Comment by adsch** [comment]
I think I got it now:

1. Select an Instrument Track and go into Arranger Overview
2. Create a new clip with "New"
3. Set the scale to chromatic
4. Press Note and pick Raindrop
5. Press "Note" and pick Sequencer
6. Now things should merge. Switch between Session and Note to see more.

I think the chromatic mode is the culprit. In the other scale modes it doesn't happen.

**Comment by git-moss** [comment]
Think I got it too :-)
The color calculation was wrong in the sequencer mode. Please test with the latest GitHub version to see if it works now.

**Comment by adsch** [comment]
Yes it is fixed now! That was quick :)
