### ISSUE TITLE
push4bitwig + Virus TI

### ISSUE THREAD

**Issue by dedeqtor** [git-moss/Push4Bitwig#163]
Hello,
I got a virus TI snow with the latest OS and bitwig 1.1.7 RC3 on windows 7 64.
also using push4bitwig ver. 4.3.

When I load the vst virus snow on an instrument channel and press some notes on
push, virus TI vst acts very strange, seems like aftertouch is interfering with
the control parameters of virus TI.

Im sending you a link to a very short video showing the problem.

https://www.dropbox.com/s/gi4bif7b28yqqm5/Video%2030-03-15%2020%2002%2019.mov?dl=0

This happens only on push, almost every pad controls a different parameter on
virus TI.

Thanks in advance for your interest.

**Comment by git-moss** [comment]
That's something you need to address directly to Bitwig.
