### ISSUE TITLE
Playhead encoder displays tempo that  can be accidentally  changed

### ISSUE THREAD

**Issue by goatgirl** [git-moss/Push4Bitwig#164]
If you touch the play head encoder above the touch strip, it will also show the tempo in the display, under the left hand encoder.  While this is displayed, turning the left hand encoder above the display will change the tempo.

I find that while I am changing a parameter using the first encoder, I will sometimes touch the playhead encoder and acccidentally change the tempo. It would be nice if this did not happen

**Comment by git-moss** [comment]
I had a hard time to reporduce this, it requires some really acrobatic skills :-)
However I deactivated them (not yet checked in).

**Comment by goatgirl** [comment]
Cool, thank you  ... I will try  to find some easy bugs next time ;)
