### ISSUE TITLE
FR: Display info box when you  touch an encoder

### ISSUE THREAD

**Issue by goatgirl** [git-moss/Push4Bitwig#165]
I have a usability enhancement that I would like to be concidered. At the moment when you move an encoder, Bitwig will show an info box on screen with the parameter and its value.

As some of the parameter names becomes rather cryptic, perhaps it would be usefull to have the info box displayed when you touch the encoder. That way you can see the full parameter name and value without having to move the encoder.

Thanks.

**Comment by git-moss** [comment]
I added on-screen notifications now for all modes (good idea!). However, they do not contain the long names because you need to decide on the text length when you register an observer at the API. This would mean to duplicate observers, which I like to prevent for a rather minor feature.

**Comment by goatgirl** [comment]
I'm sure every  little improvemnet will help.... thank you :)
