### ISSUE TITLE
Device Section Parameters 

### ISSUE THREAD

**Issue by teotigraphix** [git-moss/Push4Bitwig#167]
Doesn't exist anymore, just being helpful Moss, you probably know these things but giving you a list to check off. :)

**Comment by git-moss** [comment]
Sorry, do not understand what you mean.

**Comment by teotigraphix** [comment]
I am talking about the API that opened and closed the device parameter pages, that no longer exists in the UI so int he controller, the button does nothing.

**Comment by git-moss** [comment]
I see, good catch.

**Comment by git-moss** [comment]
Wait before removing if this function will open the new parameter edit page.

**Comment by teotigraphix** [comment]
I'm not removing anything. :)

**Comment by git-moss** [comment]
This was a note to myself :-)

**Comment by teotigraphix** [comment]
I figured as much but, I thought I would just say hi! haha

**Comment by vosc** [comment]
Good catch indeed, i think using that property for opening the new mapping editor makes totally sense ... internal Bitwig issue ID: FLOAT-9280

**Comment by git-moss** [comment]
I close this here since it is documented here: https://github.com/teotigraphix/Framework4Bitwig/issues/72
