### ISSUE TITLE
Audio track to VST cursor device in Device mode selection timing

### ISSUE THREAD

**Issue by teotigraphix** [git-moss/Push4Bitwig#168]
I don't exactly know whats going on but, I have a simple audio track, and a Komplete Kontrol VST.

Switching to the MIDI track from the Audio in Device Mode, the "Please select device" just hangs there after about 15-20 seconds it might finally show the Device mode screen.

It doesn't do this with Btiwg devices, so I am not sure it has to do with your code.

EDIT: After researching some more, it just seems like the whole device observers are really sluggish in this version.

**Comment by git-moss** [comment]
Hmm, could be that VSTs have some issues in that version. Also Kontrol is a rather weird one. Will try if I can replicate.

**Comment by git-moss** [comment]
I can reproduce it. It happens only with Kontrol. I tried it with Reaper and its fast there. Will report to Bitwig.
