### ISSUE TITLE
Sequencer: Per note automation

### ISSUE THREAD

**Issue by goatgirl** [git-moss/Push4Bitwig#169]
In the Ableton version, while in the sequncer modes, it  is possible to press and hold a note and then step automate a device parameter. This would make for a very  powerful feature and something I  would like to  see in the Bitwig script.

I  did notice there is already a similar request for press+ long hold to  change note attributes that  cannot  be implemented as yet.  This too would be a great addition when the API permits.

**Comment by teotigraphix** [comment]
Yeah if I remember this correctly it was me. :) The
framework(Framework4Bitwig) doesn't have any concept of a long press, that
needs to be implemented somehow for this to work.

**Comment by git-moss** [comment]
Sorry, this is not available in the API.
