### ISSUE TITLE
Sequencer Navigation

### ISSUE THREAD

**Issue by goatgirl** [git-moss/Push4Bitwig#170]
While using the Ableton sequencer, the navigation within the clips is done using the pads rather than the arrow keys in the Bitwig script. I  find using the pads to navigate much easier to  use.

Also, the currently  selected  clip area is highlighted in  pale yellow, which also acts as a visual clue, again making navigation within the sequencers easier to  use.

Could these be implemented in the Bitwig script at  some point?

**Comment by git-moss** [comment]
Currently not possible. I added it to the wishlist: https://github.com/teotigraphix/Framework4Bitwig/issues/71
