### ISSUE TITLE
Scale range on Push does not  match Bitwig

### ISSUE THREAD

**Issue by goatgirl** [git-moss/Push4Bitwig#171]
The octave range on the push (play track) appears to dispaly  a range 1 octave lower than what Bitwig actually  plays.

If say the C Maj scale is selected on the Push and the range is set  to  C0 to  C4. When the lowest  note (botton left  pad) is pressed, Bitwig plays this as C1, as seen in note editor.

**Comment by teotigraphix** [comment]
Wow how did we not catch that one!

**Comment by goatgirl** [comment]
Not  sure how it  was missed either, as I  spotted it  the first  day  I  used Push. It  just  took a while for it  to become annoying enough to  report ; )

I am very impressed at the speed of the fix. Thank you  very  much and very  well done  :)

**Comment by teotigraphix** [comment]
Well goatgirl, when you are looking at 10,000+ lines of code here and
there, things get missed that are obvious. :)
