### ISSUE TITLE
FR: Hide deactivated tracks

### ISSUE THREAD

**Issue by goatgirl** [git-moss/Push4Bitwig#172]
When I  have disabled tracks, there is an option button in Bitwig to  show/hide deactivated tracks. When this is set  to  hide, the tracks are no longer viewable on the mix or arranger view. However, they  are still visible on the Push session/track etc pages.  It  would be great  if these where hidden in Push, when hidden in  Bitwig.

This would be usefull in many  situations such as reducing track count for live tweeking to  preventing accidental changed to saved tracks.

I  discovered this today, though  I  am not  sure if this is possible in the script or if  this is something  that  should be requested from Bitwig. 

Many  Thanks.

**Comment by git-moss** [comment]
I can not do it in the script because when I would hide them it would conflict with the bank concept. I suggest to issue a feature request to Bitwig to hide the tracks via the API as well (which I would find a good idea, too).

**Comment by goatgirl** [comment]
Thanks moss, I thought I  was pushing my  luck for a scripted solution. I  will write to  the wizards at  Bitwig, with a nice begging letter. :)
