### ISSUE TITLE
Visual feedback delay with using APC40 MK2

### ISSUE THREAD

**Issue by engooyen** [git-moss/Push4Bitwig#173]
Setup:
APC40 MK2 with your controller script
Push with your controller script

Push -> Note mode.

The midi notes are triggering responsively, but there's a noticeable delay on the visual feedback (green light).

**Comment by git-moss** [comment]
That's a known issue, which is also known at Bitwig. But they could not look into it yet.

**Comment by engooyen** [comment]
Vielen dank!
