### ISSUE TITLE
Chords played in Note modes on some keys

### ISSUE THREAD

**Issue by phasebash** [git-moss/Push4Bitwig#174]
With a fresh install of Bitwig 1.1.8 and Push4Bitwig, I am getting chords playing when hitting single notes in Note "Play" mode.  Similarly, when touching any of the encoders, notes also play.  This is also happening in other play modes.

**Comment by phasebash** [comment]
I just discovered that if on individual tracks, the input is set to "Ableton Push" instead of "All Inputs", the parallel notes are removed.  Is this expected behavior? All notes seem to be a few semitones below the key pressed.

**Comment by git-moss** [comment]
It is not an expected behaviour. It is a known bug with Bitwig but hard to catch. It is already reported.
