### ISSUE TITLE
touch() for AutomatableRangedValue is not implemented in Device modes

### ISSUE THREAD

**Issue by teotigraphix** [git-moss/Push4Bitwig#176]
Kind of a question but the question came up on KVR and I thought this was implemented. 

The behavior Push displays in Bitwig with Touch enabled automation looks like touch(false) needs to be called to stop automation of the knobs.

**Comment by git-moss** [comment]
I do not fully understand the question (I do not use touch automation). Can you please point me to the discussion or elaborate a bit more?

**Comment by git-moss** [comment]
Found the thread.

**Comment by teotigraphix** [comment]
Nice, I was going to fix it but I don't want to create merge conflicts or stuff, in the future should I just do a pull request or something for you?

**Comment by teotigraphix** [comment]
Confirmed fix, this is fantastic, this bugged the crap out of me and I didn't realize this was the code and not Bitwig.

**Comment by git-moss** [comment]
Pull request is fine but you can also drop me a mail or assign the issue to yourself.
