### ISSUE TITLE
Flashing Device button in DeviceMode (green, grey buttons)

### ISSUE THREAD

**Issue by teotigraphix** [git-moss/Push4Bitwig#177]
I am going to try and fix this, I will let you know if I can't find it.

It's obviously linked to refreshes because when things die down and the VU stops sending updates the button is solid again.

**Comment by git-moss** [comment]
Seems also to happen when VU is off. No idea how to fix this.

**Comment by teotigraphix** [comment]
What I meant was it seems that it's related to VUs observers calling flush. Since we don't have a way to actually remove observers even though the script is not sending messages we are still getting flush() called. So the bug has to be in the update code somewhere.

**Comment by git-moss** [comment]
But why does it happen only in that mode with these buttons? If I remember correctly I exchanged in other places the color to fix this problem.

**Comment by teotigraphix** [comment]
I will test it with some variations, I don't know, and yes it seems weird that it is only happening in Device mode. But maybe that is a queue that there is something running widely at a higher abstract level of the code that deals with device params,
