### ISSUE TITLE
Per project settings.

### ISSUE THREAD

**Issue by teotigraphix** [git-moss/Push4Bitwig#178]
Hey,

I am back into the Maschine code and want to get it working with 1.2, I use per project settings for the setup.

I was wondering if you are interested in me trying to create a little mini framework that some how could impl both global and project settings and then cascade them based on project setting overrides.

**Comment by git-moss** [comment]
I am currently busy with other stuff but if you have a concept I'd like to take a look.

**Comment by git-moss** [comment]
I close this, if there is need for discussion we should move it to the F4B project.
