### ISSUE TITLE
Push 4 bitwig  - drum kit mapping

### ISSUE THREAD

**Issue by searley** [git-moss/Push4Bitwig#181]
I'm running Bitwig 1.2 and Push script 5.01, Mac Pro, OSX 10.7.5. Whatever drum rack/lit is loaded in Bitwig, the primary snare(bottom row, second from the left, on screen), is not mapped to the expected Push pad. When hitting that pad, the same snare in each kit is not triggered and no sound is made via monitoring. All other drum instruments within a kit are mapped ok on the Push.

**Comment by git-moss** [comment]
Please test if selecting "Push" as the only Midi input fixes the problem.

**Comment by searley** [comment]
Works well thx! Cheers. :-)
