### ISSUE TITLE
Color do not match drumpads

### ISSUE THREAD

**Issue by robertvandijk** [git-moss/Push4Bitwig#182]
I have had a lot of fun working with Push4Bitwig the past days. However, I run into one problem. I color coded the drum sequencer device in Bitwig. At first The colors were matched on the push controller. However, now (suddenly) there is a one octave difference and I cannot solve it. Midi notes are right: C1 base drum is triggered when I push the corresponding pad on Push, but the color is not red (as it is in Bitwig drum device).

**Comment by git-moss** [comment]
What version of the script are you running?
Can you send me your drum device?

**Comment by robertvandijk** [comment]
Thanks for the reply. I downloaded it from your website last week, so must
be the last one I assume. Hereby I send you the preset of the drummachine.

Best,
Robert

**Comment by git-moss** [comment]
I did not get an attachment. Can you please retry?

**Comment by robertvandijk** [comment]
I am not shure what you are looking for. I did send the Bitwig preset as an
attachment, maybe you need a bitwig template file: see file attached to
this email. Hope this works, otherwise let me know.

Regards,
Robert

**Comment by git-moss** [comment]
Seems attachments do not work. Please send directly to juergen.mossgraber at googlemail dot com
