### ISSUE TITLE
Arpeggiator Device can't be changed by push

### ISSUE THREAD

**Issue by JohannesTress** [git-moss/Push4Bitwig#186]
1. Create new device in new track with a Bitwig arpeggiator
2. locate the device via the push
3. velocity and gate is working fine in all 6 pages
4. Rate, Arp-Mode, Octaves, etc. are not (or only randomly) controllabla via the push...

Thanks for looking into it. After all this is an awesome work!!!

**Comment by git-moss** [comment]
Seems to be a Bitwig bug. I created a new issue here: https://github.com/teotigraphix/Framework4Bitwig/issues/105
