### ISSUE TITLE
Push 2, Inserting any device on instrument track behind intrument throws errors

### ISSUE THREAD

**Issue by adsn** [git-moss/Push4Bitwig#189]
Create an instrument on first position in chain (internal or vst), then create any audio effect behind the instrument.
Or create instrument and press ctrl g to put it into instrument layer.
Then Controller Script Console is flooded with with all parameters of first created device which can't be found.

This happens when creating devices inside Bitwig.

> restart
Called exit()
Called init()
Initialized.
Direct parameter 'CONTENTS/PW1' not found.
Direct parameter 'CONTENTS/A' not found.
Direct parameter 'CONTENTS/D' not found.
Direct parameter 'CONTENTS/S' not found.
Direct parameter 'CONTENTS/R' not found.
Direct parameter 'CONTENTS/F1FREQ' not found.
Direct parameter 'CONTENTS/F1RESO' not found.
...

**Comment by git-moss** [comment]
Yes, it is already reported and documented here: https://github.com/teotigraphix/Framework4Bitwig/issues/75
