### ISSUE TITLE
Push 2, Closing projects freezes display

### ISSUE THREAD

**Issue by adsn** [git-moss/Push4Bitwig#190]
When closing a not empty projects following error occurs:

Wrapped com.bitwig.base.control_surface.ControlSurfaceException: Invalid argument (DisplayMessage.js#27)

Then the controller script has to be restarted, otherwise the display won't update.

This doesn't happen when closing a new unsaved project which was just been created. As soon as it is saved, then closed the error occurs again.

**Comment by git-moss** [comment]
I can not reproduce that. Nervertheless, I crashed Bitwig while wildly opening and closing projects :-)
Is it a specific project or does that happen all the time? What platform are you on?

**Comment by adsn** [comment]
:)
This happens on Linux Xubuntu 15.10 with every project which has been saved before. So if I create a new one, then save it and then close it the error happens as well.
Closing new unsaved projects does not produce the error.

**Comment by git-moss** [comment]
I could reproduce it on Linux. Seems like Bitwig is setting all settings to 0 when closing a song which can create out of range values. I implemented a workaround which is online now (version 7.21).
