### ISSUE TITLE
Access to Direct parameters doesn't work with Sonic Charge Microtonic plugin vst

### ISSUE THREAD

**Issue by swap15** [git-moss/Push4Bitwig#191]
Access to Direct parameters doesn't work with Sonic Charge Microtonic plugin.
Reproduce:
1. Add Microtonic plug to instrument track
2. Press Device button on push twice and select Direct
3. Press In button on Push to enter Direct parameters of plugin
4. But I just see "Please select Device Layer..."

**Comment by git-moss** [comment]
Not a bug. 
- For multi-out plugins press Shift+"Device In". 
- Also to see the different outputs you need to create them first: Click on the 2 arrows on the device and then click on "Add missing chains".

**Comment by swap15** [comment]
Thank you for the reply! And for this cool control scripts :)
Shift + In works OK. But I think this is strange behavior... Why key shortcuts is different for multi-out plugins?
BTW I added missed chains ny click "Add missing chains" and when I press In (without shift) Push stop working properly (device and track and other buttons don't work) and after few seconds Bitwig crashes.

**Comment by git-moss** [comment]
It's different because multi out plugins have layers AND parameters.
I tested again with NIs Kontakt and could also make Bitwig crash after changing the layers some times.
I sent a crash report but please also report the problem to them.

**Comment by swap15** [comment]
I understood about layers but I talking about cases when I don't add any chains and setup layers but want work with multi channel plugins like wsingle channel. Something like this in pseudocode:

//Inside In button event
if (currentSelectedDeviceHasSubchains == false) {
  doSameAsShiftPlusInButton()
}

**Comment by git-moss** [comment]
Ah, now I see what you mean. Will need to think about it.
