### ISSUE TITLE
Selecting device in drum pad via Select + Drum pad is buggy

### ISSUE THREAD

**Issue by swap15** [git-moss/Push4Bitwig#192]
Reproduce:
1. Add Drum Machine device and add two sampler devices on C1 and C#1 pads
2. Press Select + C#1 pad for slecting sampler
3. I see "Please select Device Layer..."
4. Ok. I press Device button and see parameters os sampler
5. Press Track button by acces to Drum Pad track parameters but I switched to track parameters of Drum Machine.

**Comment by git-moss** [comment]
I am not sure if that is your bug but the layers could not be displayed when no fx send existed. Will be fixed in the next version.

**Comment by swap15** [comment]
Thank you! Waiting your next release!

**Comment by git-moss** [comment]
It's already released.

**Comment by swap15** [comment]
Just downloaded latewst release from github. Selecting drum pad still buggy. When I press shift+pad I see "Please select Device Layer...". I checked with sampler device on pads. Fx channel also added.

**Comment by git-moss** [comment]
Seems to be the old Btwig focus problem. When you click on the drum device with the mouse it works as expected.
