### ISSUE TITLE
Note PrgChng mode always sends to channel 1

### ISSUE THREAD

**Issue by agrover** [git-moss/Push4Bitwig#195]
Hi, loving my Push 1 with Bitwig, great job! Hope you don't mind some enhancement requests?

So, I'm using a multitimbral hardware instrument, I'd love to see a way to send program change to whatever channel the midi out is configured to go to, or just 2-16 in some way.

Bank change would also be handy.

Thanks for making Push4Bitwig!

**Comment by git-moss** [comment]
Bank changes can already be send with the scene buttons.

**Comment by git-moss** [comment]
The problem is that Bitwig only uses midi channel 1. Even if I send on another channel it is always changed to 1. I also tried it with the external hardware device which also sends the program changes on 1 even if the channel on the device is changed.

**Comment by agrover** [comment]
ok, thanks for looking into it in any case :smile:
