### ISSUE TITLE
Push unresponsive when Bitiwg not focussed

### ISSUE THREAD

**Issue by felixfaire** [git-moss/Push4Bitwig#197]
This may be an issue with the Controller API in general but seconds after focussing on a different program (or different desktop 'space' in OSX) the Push becomes unresponsive (eg pressing the play button does nothing, until the Bitwig window is in focus again). Sometimes the Push has erratic behaviour with unwanted lights lighting up too but only when another program has focus. I'm not sure what might be causing this (AppNap?, thread priority?) but it is incredibly frustrating as there are moments when playing live where I need to access programs other than Bitwig but still use the Push to play.

**Comment by git-moss** [comment]
Please report to Bitwig.
