### ISSUE TITLE
Up/Down when clips in arrange are selected

### ISSUE THREAD

**Issue by jerrett** [git-moss/Push4Bitwig#199]
When pushing Up or down to navigate tracks (specifically trying to drill down into track groups), if a clip is selected in arrangement view it selects the next clip in the next track.. 

which is sort of the right behaviour, but it causes problems if there are no clips.  when going into a track group is a good example - basically you can't get to the sub tracks

I think the simplest fix would be on pressing up/down to navigate tracks, it should deselect any clips in arrange first (or select the active track before going up/down - similar to clicking on the track)

**Comment by git-moss** [comment]
There is currently no access to the clips in arrangement view (only the currently selected one). Therefore, I cannot change that behaviour.
