### ISSUE TITLE
tempo/metronome pots while other things are in use

### ISSUE THREAD

**Issue by jerrett** [git-moss/Push4Bitwig#200]
I saw somewhere moss was suggesting disabling those because they are easy to hit.. .

A thought could be that if any other pots are active/touched, disable them - but otherwise allow them to work. This seems like it should be possible just by tracking the state of "how many pots are being touched", and only allowing them to work if the answer is "one" ?

**Comment by git-moss** [comment]
But you might want to tweak 2 buttons at once :-)

**Comment by jerrett** [comment]
unlikely that you would want to tweak those two + anything else... I maybe shift+touch the button to toggle the behaviour?
