### ISSUE TITLE
Using Browse on an empty track should create a new device and start the browsing session

### ISSUE THREAD

**Issue by abique** [git-moss/Push4Bitwig#201]
Using Browse on an empty track should create a new device and start the browsing session.

Also Browse on an empty project should create a new track and add the browser.

**Comment by git-moss** [comment]
Yes, please bug Volker about the necessary function 😀

**Comment by abique** [comment]
Then please tell me what you need so I can take care of it :-)

**Comment by git-moss** [comment]
He already knows :-)

**Comment by abique** [comment]
OK then I'll check that with him.

**Comment by abique** [comment]
Thank you :)

**Comment by FunkEater** [comment]
@abique any news from your discussion with Volker? I see a lot of love for the API in the last Bitwig releases. Being able to add new Device by API would be a real time saver and huge workflow improvement.

**Comment by git-moss** [comment]
Coming in v2.
