### ISSUE TITLE
Stop automation recording on knob release

### ISSUE THREAD

**Issue by abique** [git-moss/Push4Bitwig#202]
Hello,

I ask this because I saw that the automation recording does not stop once we stop touching the knob.

Thank you :)

**Comment by git-moss** [comment]
I do not quite get that. Automation is recoreded as long as "Automation Write" is activated. Do you expect that this is automatically turned off when you release the knob? But you could also want to adjust multiple knobs.

**Comment by abique** [comment]
Yes I do expect that releasing the knob stops the automation recording, but that could be configurable from bitwig.

**Comment by git-moss** [comment]
Check out the latest check-in. :-)
