### ISSUE TITLE
New step sequencer

### ISSUE THREAD

**Issue by abique** [git-moss/Push4Bitwig#203]
Hi moss,

I'd like to propose a new approach based on what Novation Circuit is doing and I think what livid base is doing as well.

The idea would be to have in the bottom two lines with the keyboard in scale for example:

C2, D2, E2, F2, G2, A2, B2, C3
C1, D1, E1, F1, G1, A1, B1, C2

I find this layout very nice and useful when you want something simple and compact.

then on the first two lines, you would have 16 steps.

When the user push a step, then if he pushes a note (bottom lines) then the sequencer should play the given note at this step.

Please have a look to the novation circuit if this is not clear.

Now we have 32 pads left for more freedom. I would see two rows (16 pads) for setting the velocity and two rows for setting the note length.

What do you think?

**Comment by git-moss** [comment]
Can you link to a video?

**Comment by abique** [comment]
https://www.youtube.com/watch?v=YNOucZtsgLo at 3:00

**Comment by git-moss** [comment]
Hi abique,
I watched the video now. This sequencer makes a lot of sense for this small amount of pads. For the 8x8 size I think its a bit too fiddly, especially that you do not see what happens in a step and you need to hands to acces it.
Cheers.
