### ISSUE TITLE
Track Infos (Sends) displayed incorrectly and not adjustable

### ISSUE THREAD

**Issue by JohannesTress** [git-moss/Push4Bitwig#210]
I updated to the recent version of the script and from that time on, the controller misbehaves when I try to adjust the send volumes of any track inside bitwig. When I touch a specific send-knob I get the view pictured in the screenshot 1. Changes of the send volume are not displayed and the actual send ammount inside bitwig can't be adjusted at all. What I expected is Screenshot 2 with actual changes displayed. Strange thing is, that after a few contacts the controller acts as expected. But this behavior is absolutely unpredictable.
![screenshot1](https://cloud.githubusercontent.com/assets/4761360/22201797/823f2b3e-e165-11e6-9e23-386ef9455c76.JPG)
![screenshot2](https://cloud.githubusercontent.com/assets/4761360/22201796/823d8054-e165-11e6-9354-81dc9a33e00a.JPG)

**Comment by git-moss** [comment]
It is already fixed on GitHub but not yet officially released.
