### ISSUE TITLE
Beta 3 - error popup

### ISSUE THREAD

**Issue by teotigraphix** [git-moss/Push4Bitwig#212]
![capture](https://cloud.githubusercontent.com/assets/226417/23046812/d784dbbc-f479-11e6-82f0-215d4a9ae2f5.PNG)

It also happened in Beta 2.

Basically I made a new track and selected it(in the DAW), the controller would not show the poly synth note grid. 

EDIT, I had an arranger clip selected when this happened, not that it makes a difference. Also I had no clip launcher clips.

**Comment by git-moss** [comment]
Yes, that's a regression in the v2 API. But I already changed this to the v2 API and if you use the latest GitHub version it will work.
